# .github/workflows/release.yml

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # FIXME: windows and macos symlinking not implemented
          #- target: x86_64-pc-windows-gnu
          #  archive: zip
          #- target: x86_64-apple-darwin
          #  archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz zip
    steps:
      - uses: actions/checkout@master

      - name: Get short SHA and tag name
        run: |
          echo TAG_NAME=$(echo '${{ github.ref }}' | sed 's#refs/tags/\(.*\)#\1#') >> $GITHUB_ENV
          echo SHORT_SHA=$(git rev-parse --short '${{ github.ref }}') >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }},ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            Short SHA: ${{ env.SHORT_SHA }}
            Full SHA: ${{ github.head }}
          draft: false
          prerelease: false

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
